<Project>
  <PropertyGroup>
    <Authors>Mel Grubb, Matthias Mueller</Authors>
    <Copyright>2021-2025 Mel Grubb, 2026 Matthias Mueller</Copyright>
    <Version>1.0.0</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <AssemblyFileVersion>$(Version).0</AssemblyFileVersion>
    <FileVersion>$(Version).0</FileVersion>
  </PropertyGroup>
</Project>